[package]
name = "webview"
version = "0.1.0"
edition = "2024"

[dependencies]
raw-window-handle = "0.6.2"
parking_lot = "0.12"
url = "2.5.4"
mime_guess = "2.0.5"

[dev-dependencies]
anyhow = "1"
minifb = "0.28.0"

[build-dependencies]
anyhow = "1"
bindgen = "0.72.0"
cc = { version = "1.2.27", features = ["parallel"] }
