[package]
name = "webview"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple"

[dependencies]
raw-window-handle = "0.6.2"
webview-sys = { path = "../sys" }
log = "0.4.25"

[dev-dependencies]
anyhow = "1"
minifb = "0.24"
